---
title: "Decision Trees and Rules"
author: "Dean Kilfoyle"
date: "6 June 2016"
output: html_notebook
---

## Rule Leaners

```{r}
## Example: Identifying Poisonous Mushrooms ----
## Step 2: Exploring and preparing the data ---- 
mushrooms <- read.csv("Chapter05/mushrooms.csv", stringsAsFactors = TRUE)

# drop the veil_type feature
mushrooms$veil_type <- NULL

# examine the class distribution
table(mushrooms$type)
```

### 1R

1R examines each feature dividing the feature into groups and finding the group with the highest frequency of the class.

1R produces if-thens but selects only a single most deterministic feature

```{r}
## Step 3: Training a model on the data ----
library(RWeka)

# train OneR() on the data
mushroom_1R <- OneR(type ~ ., data = mushrooms)
mushroom_1R

## Step 4: Evaluating model performance ----
summary(mushroom_1R)
```

### RIPPER

Generates a sequece of if-then-elses utilising multiple (as opposed to 1R single) features

```{r}
## Step 5: Improving model performance ----
mushroom_JRip <- JRip(type ~ ., data = mushrooms)
mushroom_JRip
summary(mushroom_JRip)
```


