---
title: "Regression Methods"
author: "Dean Kilfoyle"
date: "6 June 2016"
output: html_notebook
---

## Linear Regression

For predicting numeric amounts

```{r}
insurance <- read.csv("Chapter06/insurance.csv", stringsAsFactors = TRUE)

# more informative scatterplot matrix
library(psych)
pairs.panels(insurance[c("age", "bmi", "children", "expenses")])
```


### Model

```{r}
ins_model <- lm(expenses ~ age + children + bmi + sex + smoker + region, data = insurance)
summary(ins_model)
```



### Improving model performance

```{r}
# add a higher-order "age" term
insurance$age2 <- insurance$age^2

# add an indicator for BMI >= 30
insurance$bmi30 <- ifelse(insurance$bmi >= 30, 1, 0)

# create final model
ins_model2 <- lm(expenses ~ age + age2 + children + bmi + sex +
                   bmi30*smoker + region, data = insurance)

summary(ins_model2)
```


## Regression Trees and Model Trees

Each node is average value of the dependent variable

```{r}
wine <- read.csv("chapter06/whitewines.csv")
wine_train <- wine[1:3750, ]
wine_test <- wine[3751:4898, ]

## Step 3: Training a model on the data ----
# regression tree using rpart
library(rpart)
m.rpart <- rpart(quality ~ ., data = wine_train)
m.rpart
```


```{r}
# use the rpart.plot package to create a visualization
library(rpart.plot)
rpart.plot(m.rpart, digits = 3, type=3)
```



### Evaluate model performance

```{r}
# generate predictions for the testing dataset
p.rpart <- predict(m.rpart, wine_test)

# compare the correlation
cor(p.rpart, wine_test$quality)
```

## m5 model tree

Now each node will be a multiple linear regression rather than simply the mean value

```{r}
library(RWeka)
m.m5p <- M5P(quality ~ ., data = wine_train)

# display the tree
m.m5p
```


```{r}
# generate predictions for the model
p.m5p <- predict(m.m5p, wine_test)

# summary statistics about the predictions
summary(p.m5p)

# correlation between the predicted and true values
cor(p.m5p, wine_test$quality)

# mean absolute error of predicted and true values
# (uses a custom function defined above)
MAE(wine_test$quality, p.m5p)
```

