---
title: "kNN"
author: "Dean Kilfoyle"
date: "6 June 2016"
output: 
  html_notebook: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## kNN

k nearest neighbours. Distance is calculated using euclidian distance. k is chosen by user. Run a sample dataset

```{r load.model}
wbcd <- read.csv("wisc_bc_data.csv", stringsAsFactors = FALSE)
# drop the id feature
wbcd <- wbcd[-1]
wbcd$diagnosis <- factor(wbcd$diagnosis, levels = c("B", "M"), labels = c("Benign", "Malignant"))
```

## Training the model

```{r}
# normalize
wbcd_n <- as.data.frame(scale(wbcd[-1]))

# create training and test data
wbcd_train <- wbcd_n[1:469, ]
wbcd_test <- wbcd_n[470:569, ]

wbcd_train_labels <- wbcd[1:469, 1]
wbcd_test_labels <- wbcd[470:569, 1]

library(class)
wbcd_test_pred <- knn(train = wbcd_train, test = wbcd_test, cl = wbcd_train_labels, k = 21)
```

## Evaluating model performance

```{r}
library(gmodels)

# Create the cross tabulation of predicted vs. actual
CrossTable(x = wbcd_test_labels, y = wbcd_test_pred, prop.chisq = FALSE)
```
